### ISSUE TITLE
vnote  crash when read(render) note include latex formula

### ISSUE THREAD

**Issue by shilkazx** [vnotex/vnote#804]
OS Version (操作系统): Windows, Linux, macOS
Archlinux

VNote Version (Help - About VNote - Version: )(VNote版本): 2.2,  d78e892d5cc  etc..
v2.5 installed from AUR vnote-bin package

Symptoms (表现):
 crash. bug might be in nouveau driver or mesa library.

How to Repro (如何复现):
open a note include latex formula then maximize vnote window.

gdb trace:
Thread 19 "Chrome_InProcGp" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffa4ff9700 (LWP 2804)]
0x00007fffe546fbf7 in ?? () from /usr/lib/dri/nouveau_dri.so
(gdb) bt full
#0  0x00007fffe546fbf7 in ?? () from /usr/lib/dri/nouveau_dri.so
No symbol table info available.
#1  0x00007fffe54943c4 in ?? () from /usr/lib/dri/nouveau_dri.so
No symbol table info available.
#2  0x00007fffe54ba321 in ?? () from /usr/lib/dri/nouveau_dri.so
No symbol table info available.
#3  0x00007fffe5128f51 in ?? () from /usr/lib/libdrm_nouveau.so.2
No symbol table info available.
#4  0x00007fffe5129b7f in ?? () from /usr/lib/libdrm_nouveau.so.2
No symbol table info available.
#5  0x00007fffe512abb0 in nouveau_pushbuf_kick () from /usr/lib/libdrm_nouveau.so.2
No symbol table info available.
#6  0x00007fffe54ba7c7 in ?? () from /usr/lib/dri/nouveau_dri.so
No symbol table info available.
#7  0x00007fffe572a602 in ?? () from /usr/lib/dri/nouveau_dri.so
No symbol table info available.
#8  0x00007ffff1d74114 in ?? () from /opt/vnote/usr/bin/../lib/libQt5WebEngineCore.so.5
No symbol table info available.
#9  0x00007ffff1d10685 in ?? () from /opt/vnote/usr/bin/../lib/libQt5WebEngineCore.so.5
No symbol table info available.
#10 0x00007ffff1d107a8 in ?? () from /opt/vnote/usr/bin/../lib/libQt5WebEngineCore.so.5
No symbol table info available.
#11 0x00007ffff1c943b1 in ?? () from /opt/vnote/usr/bin/../lib/libQt5WebEngineCore.so.5
No symbol table info available.
#12 0x00007ffff1cc84d8 in ?? () from /opt/vnote/usr/bin/../lib/libQt5WebEngineCore.so.5
No symbol table info available.
#13 0x00007ffff1d2b8db in ?? () from /opt/vnote/usr/bin/../lib/libQt5WebEngineCore.so.5
No symbol table info available.
#14 0x00007ffff1c813f5 in ?? () from /opt/vnote/usr/bin/../lib/libQt5WebEngineCore.so.5
No symbol table info available.
#15 0x00007ffff428aa28 in ?? () from /opt/vnote/usr/bin/../lib/libQt5WebEngineCore.so.5
No symbol table info available.
#16 0x00007ffff428e229 in ?? () from /opt/vnote/usr/bin/../lib/libQt5WebEngineCore.so.5
No symbol table info available.
#17 0x00007ffff420ee97 in ?? () from /opt/vnote/usr/bin/../lib/libQt5WebEngineCore.so.5
No symbol table info available.
#18 0x00007ffff42886f2 in ?? () from /opt/vnote/usr/bin/../lib/libQt5WebEngineCore.so.5
No symbol table info available.
#19 0x00007ffff42887ae in ?? () from /opt/vnote/usr/bin/../lib/libQt5WebEngineCore.so.5
No symbol table info available.
#20 0x00007ffff13344a3 in ?? () from /opt/vnote/usr/bin/../lib/libQt5WebEngineCore.so.5
No symbol table info available.
#21 0x00007ffff12d9ca0 in ?? () from /opt/vnote/usr/bin/../lib/libQt5WebEngineCore.so.5
No symbol table info available.
#22 0x00007ffff12dbaad in ?? () from /opt/vnote/usr/bin/../lib/libQt5WebEngineCore.so.5
No symbol table info available.
#23 0x00007ffff12dc9a6 in ?? () from /opt/vnote/usr/bin/../lib/libQt5WebEngineCore.so.5
No symbol table info available.
#24 0x00007ffff12dcce9 in ?? () from /opt/vnote/usr/bin/../lib/libQt5WebEngineCore.so.5
No symbol table info available.
#25 0x00007ffff12d90a2 in ?? () from /opt/vnote/usr/bin/../lib/libQt5WebEngineCore.so.5
No symbol table info available.
#26 0x00007ffff12f48d8 in ?? () from /opt/vnote/usr/bin/../lib/libQt5WebEngineCore.so.5
No symbol table info available.
#27 0x00007ffff130c4f6 in ?? () from /opt/vnote/usr/bin/../lib/libQt5WebEngineCore.so.5
No symbol table info available.
--Type <RET> for more, q to quit, c to continue without paging--
#28 0x00007ffff13087ad in ?? () from /opt/vnote/usr/bin/../lib/libQt5WebEngineCore.so.5
No symbol table info available.
#29 0x00007fffefcb0a92 in start_thread () from /usr/lib/libpthread.so.0
No symbol table info available.
#30 0x00007ffff692ccd3 in clone () from /usr/lib/libc.so.6
No symbol table info available.

**Comment by tamlok** [comment]
I think it is caused by display driver, too. Similar issue was reported previously. VNote has some requirements for openGL.

**Comment by shilkazx** [comment]
> I think it is caused by display driver, too. Similar issue was reported previously. VNote has some requirements for openGL.

Thanks for reply. Seems nothing can help other than change graphic card driver?

**Comment by tamlok** [comment]
I am afraid so.
